### ISSUE TITLE
[Bug]: could not start dn

### ISSUE THREAD

**Issue by EZ4BRUCE** [matrixorigin/matrixone-operator#291]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93): operator(latest), mo(nightly-78c9058a)
- Hardware parameters: 
- OS type: macos
- Others: running on kind

### Actual Behavior

i follow this [article](https://github.com/matrixorigin/matrixone-operator/blob/main/docs/getting_started.md) to start mo cluster, everything just work fine until the dn crash, here are the logs:

```
{"level":"ERROR","time":"2022/12/23 09:08:27.150317 +0000","name":"dn-service","caller":"log/logger.go:123","msg":"txn read failed","uuid":"00000000-0000-0000-0000-100000000000","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.mo.svc:41010","txn":"9d40a8761fd94f749a4bb38528818a99/Active/S:1671786507148715385-0","error":"not connect to a database"}
{"level":"ERROR","time":"2022/12/23 09:08:27.150412 +0000","caller":"memorystorage/mem_handler.go:1023","msg":"error: not connect to a database","stacktrace":"github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*MemHandler).HandleOpenDatabase\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/mem_handler.go:1023\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*CatalogHandler).HandleOpenDatabase\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/catalog_handler.go:433\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.handleRead[...]\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/read.go:133\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*Storage).Read\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/read.go:33\ngithub.com/matrixorigin/matrixone/pkg/txn/service.(*service).Read\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:58\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).doRead\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:77\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWithRetry\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:184\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleRead\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:58\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:161\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:204\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344"}
{"level":"ERROR","time":"2022/12/23 09:08:27.150486 +0000","name":"dn-service","caller":"log/logger.go:123","msg":"txn read failed","uuid":"00000000-0000-0000-0000-100000000000","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.mo.svc:41010","txn":"6045e1fbb41f41d898e481274311b971/Active/S:1671786507149432468-0","error":"not connect to a database"}
{"level":"ERROR","time":"2022/12/23 09:08:27.150586 +0000","caller":"memorystorage/mem_handler.go:1023","msg":"error: not connect to a database","stacktrace":"github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*MemHandler).HandleOpenDatabase\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/mem_handler.go:1023\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*CatalogHandler).HandleOpenDatabase\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/catalog_handler.go:433\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.handleRead[...]\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/read.go:133\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage.(*Storage).Read\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/read.go:33\ngithub.com/matrixorigin/matrixone/pkg/txn/service.(*service).Read\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:58\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).doRead\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:77\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWithRetry\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:184\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleRead\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:58\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:161\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:204\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344"}
{"level":"ERROR","time":"2022/12/23 09:08:27.150654 +0000","name":"dn-service","caller":"log/logger.go:123","msg":"txn read failed","uuid":"00000000-0000-0000-0000-100000000000","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.mo.svc:41010","txn":"08ad27390a0f4a40a2a981de4f6b4094/Active/S:1671786507149960677-0","error":"not connect to a database"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ccf944]

goroutine 118 [running]:
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Read(0x4002f66000, {0x27f2098, 0x4002fc07e0}, 0x4002f6e000, 0x40005ce000)
    /go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:64 +0x604
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).doRead(0x40048733b8?, {0x27f2098, 0x4002fc07e0}, 0x4002f6e000, 0x40005ce000)
    /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:77 +0x8c
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWithRetry(0x4004873448?, {0x27f2098, 0x4002fc07e0}, 0x4002f75e00?, 0x40005ce000, 0x4004873448)
    /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:184 +0xc0
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleRead(0x4002f51250?, {0x27f2098?, 0x4002fc07e0?}, 0x239ca20?, 0x4002f6aea0?)
    /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:58 +0x3c
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0x4002f51200, {0x27f2098?, 0x4002fc07e0?}, {0x2818de8?, 0x4002f6e000?}, 0x8fda60?, {0x27b42e0, 0x40031b7400})
    /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:161 +0x434
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0x4002f51320, {0x283d620, 0x40005ee100}, {0x22a3fe0?, 0x4002fc0810}, 0x3d)
    /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:204 +0x644
github.com/fagongzi/goetty/v2.(*server).doConnection(0x4002f5b180, {0x283d620, 0x40005ee100})
    /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x2b8
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
    /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x78
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
    /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x3a4
Stream closed EOF for mo/mo-dn-0 (main)

```

**Comment by aylei** [comment]
closed by https://github.com/matrixorigin/matrixone-operator/pull/293
