### ISSUE TITLE
[Bug]: Failed to start MO when set logService.replicas = 1 in MatrixOneCluster CRD

### ISSUE THREAD

**Issue by jinqinghui** [matrixorigin/matrixone-operator#300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93):sha-c939c87
- Hardware parameters:
- OS type:
- Others:

### Actual Behavior

Failed to start log pod when set logService.replicas = 1 in MatrixOneCluster CRD

### Expected Behavior

MO success start all pods.

### Steps to Reproduce

mo.yaml:
```
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
...
  logService:
    replicas: 1
...
```
kubectl apply -f mo.yaml

**Comment by aylei** [comment]
Add an E2E test to verify this case

**Comment by aylei** [comment]
`make e2e`

**Comment by loveRhythm1990** [comment]
when I set `logService.replicas=1`,  I found following error. after ask @volgariver6 for help, he told me that we should set `gossip-allow-self-as-seed = true` when these is only one replicas, I have test it and it works, I will promote a pr to fix it and add e2e test.

```/mo-service -cfg /tmp/tmp.5TrGUVNHI2
{"level":"ERROR","time":"2023/03/22 03:13:50.649584 +0000","name":"log-service",
"caller":"logservice/service.go:108",
"msg":"failed to create log store","uuid":"00000000-0000-0000-0000-000000000000",
"error":"no valid seed node",
"errorVerbose":"no valid seed node"

 attached stack trace
 -- stack trace:
|github.com/lni/dragonboat/v4/config.(*GossipConfig).Validate
\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/config/config.go:1011
github.com/lni/dragonboat/v4/config.(*NodeHostConfig).Validate\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/config/config.go:575\n  | github.com/lni/dragonboat/v4.NewNodeHost\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:308\n  | github.com/matrixorigin/matrixone/pkg/logservice.newLogStore\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:146\n  | github.com/matrixorigin/matrixone/pkg/logservice.NewService\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:106\n  | main.startLogService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:231\n  | main.startService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:148\n  | main.main\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:95\n  | runtime.main\n  | \t/usr/local/go/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1594\nWraps: (2) no valid seed node\nError types: (1) *withstack.withStack (2) *errutil.leafError","stacktrace":"github.com/matrixorigin/matrixone/pkg/logservice.NewService\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:108\nmain.startLogService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:231\nmain.startService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:148\nmain.main\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
panic: no valid seed node

goroutine 1 [running]:
main.startLogService(0xc003170d00, 0xc000188000?, {0x2cbb560, 0xc00363fe78})
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:234 +0x249
main.startService(0x7ffd026a9b13?, 0x4?)
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:148 +0xfa
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:95 +0x298```
