### ISSUE TITLE
[Bug]: controller-gen panic when using go 1.22

### ISSUE THREAD

**Issue by cyberchen98** [matrixorigin/matrixone-operator#507]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

### Actual Behavior
```
make helm-pkg
cd api && make manifests
/Users/wangchen/workspace/matrixorigin/matrixone-operator/api/bin/controller-gen crd:crdVersions=v1 rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=../deploy/crds output:webhook:artifacts:config=../deploy/webhook
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105188d14]

goroutine 132 [running]:
go/types.(*Checker).handleBailout(0x14000653800, 0x14000a25d18)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x105453a60?, 0x1059dbf30?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x10551cc70, 0x1059e4860})
        /usr/local/go/src/go/types/sizes.go:228 +0x314
......
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x0?)
        /Users/wangchen/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 1
        /Users/wangchen/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:260 +0x230
make[1]: *** [manifests] Error 2
make: *** [manifests] Error 2
```

### Additional information

I have noticed that this is caused by a breaking change in go1.22 [#61035](https://github.com/golang/go/issues/61035) and the downstream application `controller-gen` has already fixed this issue. However, we are also using `crd-ref-docs`, which depends on a lower version of `controller-gen`, and it is uncertain whether they will immediately fix this problem. Before the go team completely resolves this issue, the most convenient solution may be downgrading to go1.21.

**Comment by cyberchen98** [comment]
fixed in #525
